services:
  app1:
    build: .
    image: nests-lb
    restart: unless-stopped
    env_file: .env
    environment:
      - INSTANCE_ID=1
      - PORT=4500
      - REDIS_HOST=redis
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - MONGODB_URL_FILE=/run/secrets/mongodb_url
    secrets:
      - jwt_secret
      - mongodb_url
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '2'

  app2:
    build: .
    image: nests-lb
    restart: unless-stopped
    env_file: .env
    environment:
      - INSTANCE_ID=2
      - PORT=4501
      - REDIS_HOST=redis
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - MONGODB_URL_FILE=/run/secrets/mongodb_url
    secrets:
      - jwt_secret
      - mongodb_url
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '2'

  app3:
    build: .
    image: nests-lb
    restart: unless-stopped
    env_file: .env
    environment:
      - INSTANCE_ID=3
      - PORT=4502
      - REDIS_HOST=redis
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - MONGODB_URL_FILE=/run/secrets/mongodb_url
    secrets:
      - jwt_secret
      - mongodb_url
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '2'

  app4:
    build: .
    image: nests-lb
    restart: unless-stopped
    env_file: .env
    environment:
      - INSTANCE_ID=4
      - PORT=4503
      - REDIS_HOST=redis
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - MONGODB_URL_FILE=/run/secrets/mongodb_url
    secrets:
      - jwt_secret
      - mongodb_url
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '2'

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
      - app4

secrets:
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  mongodb_url:
    file: ./secrets/mongodb_url.txt

volumes:
  redis_data:
