events {

}

http{
    # now as we are going to use the load balancing means more than one instance
    upstream backend{
        server app1:4500;
        server app2:4501;
        server app3:4502;
        server app4:4503;
        server app5:4504;
        server app6:4505;
        server app7:4506;
        server app8:4507;
    }
    server{
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}